### PR TITLE
Add the aura/html helpers to the view

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by pmjones** [comment]
I think it is better if a library only handles its own configuration; it cannot depend on other libraries being present. This kind of thing is better suited to a Project or Bundle.

**Comment by harikt** [comment]
So @pmjones how do you integrate the aura/view and aura/html in the project ?

**Comment by pmjones** [comment]
The developer would add that to the project-level config, or write a bundle that does it and then load the bundle.

**Comment by pmjones** [comment]
To be clear, the config code you give above is correct; I just don't think it belongs in the View library.

**Comment by harikt** [comment]
Hm. @pmjones you know we are making a lot of configurations happening to make things work. 

Recently I was hearing a NomadPHP talk by D Keith Casey Jr . He was mentioning about shortest possible implementation to make things work in 5 minutes or less.

Because you / me / others can get distracted in less than a few minutes and we will blame things that we spend hours in it ( not mentioning we spend much time on other stuffs than learning the same ) . 

So this is a similar problem I am seeing to get things done when making the project.

**Comment by pmjones** [comment]
I hear you. Even so, we cannot depend on another library being present. We just don't know if it's there or not.  At the _bundle_ level, where we know it's a dependency, or at the _project_ level, we where have installed it ourselves, then it's appropriate. But not at the _library_ level.

**Comment by harikt** [comment]
ok. agreed.

**Pull request closed without merging**
