### PR TITLE
update travis

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by harikt** [comment]
This could have been just made with trusty in the front. But not sure when will trusty remove old php version. ie why.

@jakejohns , @pmjones any thoughts ?

**Comment by jakejohns** [comment]
This isn't particularly on topic, but related. 

From @pmjones [In March 2015 ](http://auraphp.com/blog/2015/03/27/aura-3-plans/):
> 2.x packages with existing stable releases will continue to be the center of development activity for the foreseeable future, including fixes and features.

Is this still true? In that post it is also stated that 5.6 will be the minimum for 3.x. The post also warns of the dangers of "getting on the latest-release bandwagon". However, version < 5.6 haven't been supported for years now, and 5.6 support ends in 2018. 

At the point that we need to jump through hoops to get our CI to work because we're trying to both support current and unsupported versions of PHP, perhaps we should review the roadmap.

Are we waiting for a feature request necessitating a 3.x transition?
Why don't we clean up some of these 2.x packages and push them into the future with 3.x releases?

If I'm not mistaken, with 5.6 as a minimum version, I believe trusty will just work, rather than requiring these more convoluted multi distribution travis configs, like the magic @harikt worked out for aura/html

**Comment by harikt** [comment]
@jakejohns I am not in favor of 5.x versions if we are doing a major release. I think it is time to push to 7.x. But I know @pmjones have a different opinion on the subject. I don't know what is his current thoughts though.

**Comment by harikt** [comment]
Merging this PR, so other PR's will run on PHP 7.

**Pull request merged**
