### PR TITLE
Add fluency to links helper add method

### PR DESCRIPTION
**Pull request by jelofson**
Thought it might be handy to use the links helper fluently
Rather than...

``` php
$links = $this->links();
$links->add($attribs);
$links->add($otherattribs);
echo $links->get();
```

Do this

``` php
echo $this->links()
               ->add($attribs)
               ->add($otherattribs)
               ->get();
```

What do you think? Seem reasonable?

### CODE REVIEW

**Comment by jelofson** [comment]
I just noticed several other helpers aren't fluent either. Maybe you want to ignore this PR and leave it non-fluent to match the other helpers?

**Comment by harikt** [comment]
fluent seems a nice way. We should wait to hear @pmjones thoughts for a merge. Also this is currently coming to master branch. But it should go to develop. 

Thanks

**Comment by pmjones** [comment]
Like @harikt says, it should go against "develop" not "master".

I have no problem with fluency being added, but it should probably be on all of them, not just some of them.

Having said that, if the issue is "being able to add a lot of links with a single method call" then perhaps what we need is the equivalent of an "addMany()" that takes an array of arrays, and loops internally to call "add()".

**Comment by pmjones** [comment]
This seems to be obviated by #44. Let me know if that's not the case.

**Pull request closed without merging**
