### PR TITLE
add .phtml template search support

### PR DESCRIPTION
**Pull request by jimbojsb**

### CODE REVIEW

**Comment by pmjones** [comment]
(/me ponders)

If I may ask, what's the situation that led to this PR?

**Comment by jimbojsb** [comment]
I have 5 years worth of .phtml files from ZF1 / Zend_View. I wanted to start subbing in Aura in places that are feasible, but I'd still like to be able to access partials and such without having to rename everything and change our "standard". I also considered implementing this as a configuration option, as I do realize that if you have alot of search paths this way may require up to 2x as many stats on the filesystem.

**Comment by pmjones** [comment]
/me nods

The problem from my perspective is that if it supports one alternative extension, there will be a clamoring for it to support other alternative extensions.

To support your use-case, then, I think it might be better to make it a configurable option, rather than hard-coding it.
1. Would that be useful to you?
2. Should it support multiple extensions a la `$exts = ['.php', '.phtml']` or just one a la `$ext = '.php'` ? (I admit I like the latter better.)

**Comment by jimbojsb** [comment]
Configuration would be perfectly fine, I'm happy to rebuild the feature in that way. I have no need for multiple extensions at once, and I suspect most other people would be in the same boat (pick one thing and stick with it)

**Comment by pmjones** [comment]
Agreed. I'd say a constructor param named something sensible (`$ext` ?) defaulting to `.php`, retained as a property, and used as needed. If you think a setter would be better, go for it. As usual, I retain the right of review. ;-)

**Comment by jimbojsb** [comment]
@pmjones are there docs somewhere on the preferred way to run tests locally? I got them to run but it seemed like it was going to leave artifacts and such. Seems like it should have phpunit as a dev dependency and have phpunit.xml in the gitignore?

**Comment by harikt** [comment]
@jimbojsb I hope you have phpunit installed globally.

Run phpunit from the root .

Assuming you did

```
git clone https://github.com/auraphp/Aura.View
cd Aura.View
composer dumpautoload
phpunit
```

ie it. Let me know if that helps.

Edit : do `composer dumpautoload` though it is need really needed. Not sure why @pmjones  added `vendor/autoload.php` when there is no dependency. May be consistency.

**Comment by jimbojsb** [comment]
re-implemented as a property / setter defaulted to the existing '.php'

**Comment by pmjones** [comment]
Nice. I reserve the right to change the method & property names, but other than that, we're good. Thanks!

**Comment by jimbojsb** [comment]
Thanks for merging. Any idea when I might expect that in a versioned release? I'm going to point my feature branch at that commit hash for now.

**Comment by harikt** [comment]
aah I get why the `vendor/autoload.php` comes. It was for testing the config.

**Pull request merged**
