### PR TITLE
Experimental (better, branched it and fixed a PSR error)

### PR DESCRIPTION
**Pull request by belgianguy**
Now I did a correct branch so I don't soil the develop branch with experimental tinkering.

Also fixed a PSR error in Checkboxes.php (the inline if statements in the for loop in invoke() )

Here are the other PSR errors that showed up, which supposedly were already in before the fork:

http://pastebin.com/ecBJvMuL

### CODE REVIEW

**Comment by harikt** [comment]
@belgianguy so you can close the other PR then ?

The only error which I notice in the pastie is 

```
FILE: Aura.View/src/Aura/View/Helper/Form/Input/Value.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 38 | ERROR | Whitespace found at end of line
```

The rest of the errors can be ignored ;) .

**Comment by belgianguy** [comment]
I closed the other (older) PR, is it still active? Did I forget something?

The hard part about recommendations is the way people interpret them, you have some hardliners and some who take a more relaxed approach.

**Comment by harikt** [comment]
@belgianguy Thank you for the PR.

I am sorry if you felt the words were hard. I noticed it now only the other PR was closed.

Thank you.

**Comment by belgianguy** [comment]
Oh, I didn't mean to sound mean, if so, my apologies! You were very helpful, both here and on IRC. So no worries there!

**Comment by harikt** [comment]
No worries, I am running on a hard time. So I will also read messages
incorrectly.

Thanks

_Hari K T_

http://harikt.com , https://github.com/auraphp

**Pull request merged**
