### PR TITLE
Helper updates

### PR DESCRIPTION
**Pull request by jelofson**
I added a markdown document for most of the helpers. It's a work in progress for sure.
I added fluency to some of the helpers and updated the tests.
I fixed the ordering of the styles helper to match that of the scripts helper. It was sorting via the tag first, then position. I think it should sort via the position, and then by the order it was added to the array. Would you agree?

I also fixed a 'bool' in the checkboxes and radios helper for the 'checked' parameter. 

I probably should have had a single pr for some of these commits. I hope this one is ok. Also, I fixed my develop branch so it should work properly with the auraphp:develop branch.

### CODE REVIEW

**Comment by harikt** [comment]
Hey @jelofson ,

> I added a markdown document for most of the helpers. It's a work in progress for sure.

Nice to see. I feel it needs to be in updated in README.md itself. Else the documentation will have some issues ?

> I added fluency to some of the helpers and updated the tests.

Thanks

> I fixed the ordering of the styles helper to match that of the scripts helper. It was sorting via the tag first, then position. I think it should sort via the position, and then by the order it was added to the array. Would you agree?

Any BC break via this? If so no :) .

> I also fixed a 'bool' in the checkboxes and radios helper for the 'checked' parameter.

Was this a bug fix ?

> I probably should have had a single pr for some of these commits. 

Yes single PR will make sense.

> I hope this one is ok. Also, I fixed my develop branch so it should work properly with the auraphp:develop branch.

For the current time, it is ok. Let us see what @pmjones thinks about this.

**Comment by jelofson** [comment]
> Nice to see. I feel it needs to be in updated in README.md itself. Else the documentation will have some issues?

I agree. For the moment, it might be worth reading the document over and seeing if it all makes sense and how to best incorporate it. I was wondering if there was a way to link to a second document from the main readme. It could get very long otherwise. There are also a few little updates I could do for the main readme. There is talk of wrapping the input in an optional label, but that is not completely correct. 

```
// from the readme
$this->input($attribs, $value, $label, $label_attribs) 
// returns an <input> tag, optionally wrapped in a <label> tag
// this is not presently correct
```

> Any BC break via this? If so no :) .

I can't see any BC issues. I actually noticed it when writing the unit test. The order of the styles was not what I expected. We can run more tests and be double sure it is outputting the expected results. Heck, maybe my expected results are different than someone else :)

> Was this a bug fix ?

No, not a bug fix. Just a typo in the php documentation for the method. The code documentation suggested the "$checked" value should be a bool which is not the case. In the checkboxes helper, it's an array, and in the radios helper, it's a string. 

Yes, I am happy to see what Paul's comments are.

**Comment by pmjones** [comment]
This one's a monster! :-) It's daunting to look over it all at once; give me some time to review.

**Comment by pmjones** [comment]
We can easily link from the main README.md to Helpers.md; for example, in the README:

```
Please see the [helpers docs](Helpers.md) for blah blah blah.
```

(Relative filename URL in the parens.)

**Comment by jelofson** [comment]
Ya, it wasn't supposed to snowball quite that much :) Hopefully we can use some of it in some fashion. 

I saw your other msg regarding fluency and I am totally open to an addMany() method too. Whatever you prefer...

**Comment by pmjones** [comment]
The changes I see are:
- Added Helpers.md file
- Fixed some docblocks
- Made fluent: Links::add(), Metas::add(), Metas::addHttp(), Metas::addName(),
  Scripts::add(), Scripts::addCond(), Styles::add(), Styles::addCond()
- Styles::add(), addCond(), and get() modify how sorting gets done
- Added new tests, but no changes to existing tests

Does that about sum it up?

**Comment by jelofson** [comment]
Looks correct to me...

**Pull request merged**
