### PR TITLE
New method to add data to existing data in TwoStep

### PR DESCRIPTION
**Pull request by jelofson**
Also added new test and ran codesniffer. Hopefully this PR is against the correct branch.

### CODE REVIEW

**Comment by harikt** [comment]
@jelofson not sure how other commits are shown in the branch.

**Comment by jelofson** [comment]
Let me redo it. You can remove that pr and I will do it over. Sound good?

On 9/27/13, Hari K T notifications@github.com wrote:

> @jelofson not sure how other commits are shown in the branch.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/auraphp/Aura.View/pull/40#issuecomment-25285568

## 

Sent from my mobile device

**Comment by harikt** [comment]
Wait to hear @pmjones thoughts , and then redo it ?

_Hari K T_

http://harikt.com , https://github.com/auraphp

**Comment by pmjones** [comment]
Superseded by later pull request.

**Pull request closed without merging**
